#!/bin/sh

CHARGING=`acpi -a | awk -F' ' '{print $3}'`
PERCENTAGE=`acpi -b | awk -F',' '{print $2}' | awk -F' ' '{print $1}'`
PERCENT=`acpi -b | awk -F',' '{print $2}' | awk -F' ' '{print $1}' | awk -F'%' '{print $1}'`
TIME=`acpi -b | awk -F',' '{print $3}' | awk -F' ' '{print $1}'`

#echo "$CHARGING $PERCENTAGE $TIME"

if [ "$CHARGING" == "on-line" ]; then
  symbol=""
elif [ "$CHARGING" == "off-line" ]; then
  symbol=""
fi


if [[ "$PERCENT" = "100" ]]; then
	symbol="$symbol"

elif [[ "$PERCENT" -ge "75" ]]&& [[ "$PERCENT" -lt "100" ]]; then
  symbol="$symbol"
  
elif [[ "$PERCENT" -ge "50" ]] && [[ "$PERCENT" -lt "75" ]]; then
  symbol="$symbol"
  
elif [[ "$PERCENT" -ge "25" ]] && [[ "$PERCENT" -lt "50" ]]; then
  symbol="$symbol"
  

elif [[ "$PERCENT" -gt "0" ]] && [[ "$PERCENT" -lt "25" ]]; then
  symbol="$symbol"
  fi

if [[ "$TIME" = "until" ]]; then
	echo "$symbol $PERCENTAGE Charged"
else
	echo "$symbol $PERCENTAGE $TIME"
fi
